## What is Numpy?
NumPy is a Python library used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices.It is used for scientific computing i.e. engineering mathematics. Most important thing in this is Numpy array.

## Creating Numpy Arrays:
* np.array([])
* np.arange()
* np.arrange().reshape()
* np.ones(())
* np.zeros(())
* np.random.random()
* np.linspace()
* np.identity()

In [ ]:
import numpy as np
#create a 1D array using np.array
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
#creating array using arange function
arr2 = np.arange(1,11)
print(arr2)
arr3 = np.arange(1,11,2)
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [ ]:
#creating 2D array
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#creating 2D array using arange function
matrix2 = np.arange(1,15).reshape(2,7)
print(matrix2)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
arr4 = np.arange(1,13).reshape(3,4)
print(arr4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#creating unit matrix using ones function
arr5 = np.ones((3,4))
arr5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#changing data type of an array using dtype (default dtype is float)
arr6 = np.ones((3,3),dtype=int)
arr6

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
#creating null matrix using zeroes function
arr7 = np.zeros((4,4),dtype = int)
arr7

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
#creating a 2*4 matrix with random float numbers
arr8 = np.random.random((2,4))
arr8

array([[0.4653838 , 0.01745481, 0.48699127, 0.62219702],
       [0.079835  , 0.99289366, 0.48896102, 0.85342538]])

In [ ]:
#size attributes specify the order & 0,100 gives the range of numbers
arr9 = np.random.randint(0,100,size=(3,4))
print(arr9)

[[99 64 93  1]
 [99 30 29  4]
 [74 46 10 28]]


In [ ]:
#The np.linspace function in NumPy is used to generate
#an array of evenly spaced values over a specified range
arr10 = np.linspace(0,10,4)
print(arr10)

[ 0.          3.33333333  6.66666667 10.        ]


In [ ]:
arr10 = np.linspace(0,10,4,dtype=int)
print(arr10)

[ 0  3  6 10]


In [ ]:
#creating an identity matrix
arr11 = np.identity(5)
print(arr11)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## Array Attributes
* ndim
* shape
* size
* itemsize
* dtype
* astype(np.int32)


In [ ]:
Ar1 = np.arange(10,dtype = int) #1D array
Ar2 = np.arange(16, dtype = int).reshape(4,4) #2D array
Ar3 = np.arange(8,dtype=int).reshape(2,2,2) #3D array
print(Ar1)
print(Ar2)
print(Ar3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
#ndim: returns the number of dimensions (axes) of the array.
print(np.ndim(Ar3))
print(np.ndim(Ar2))
print(np.ndim(Ar1))

3
2
1


In [ ]:
#shape: returns a tuple representing the dimensions of the array (rows, columns).
print(Ar2)
print(Ar2.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
(4, 4)


In [ ]:
#size: returns the total number of elements in the array.
print(Ar2.size)

16


In [ ]:
#itemsize: returns the size (in bytes) of each element in the array.
print(Ar2.itemsize)

8


In [ ]:
#dtype: eturns the data type of the array elements.
print(Ar2.dtype)

int64


In [ ]:
#astype(): Converts the array to a specified data type.
#It creates a new array with the desired type without
#modifying the original array.
new_Ar2 = Ar2.astype(float)
print(new_Ar2,new_Ar2.dtype)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]] float64


## Array Operations
* Scalar Operations
* Arithmetic Operations
* Relational Operations
* Vector Operations

In [ ]:
matrix1 = np.arange(1,13).reshape(4,3)
matrix2 = np.arange(13,25).reshape(4,3)
print(matrix1)
print(matrix2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]]


In [ ]:
#scalar operations
print(matrix1 + 3)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [ ]:
print(matrix2 - 3)

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]


In [ ]:
print(matrix1*2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]]


In [ ]:
print(matrix1 / 2)

[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]
 [5.  5.5 6. ]]


In [ ]:
print(matrix1**2)

[[  1   4   9]
 [ 16  25  36]
 [ 49  64  81]
 [100 121 144]]


In [ ]:
print(matrix1 % 2)

[[1 0 1]
 [0 1 0]
 [1 0 1]
 [0 1 0]]


In [ ]:
#arithmetic operations
print(matrix1 + matrix2)

[[14 16 18]
 [20 22 24]
 [26 28 30]
 [32 34 36]]


In [ ]:
print(matrix1 % matrix2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
#relational operations
equal = matrix1 > 5
print(equal)

[[False False False]
 [False False  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
greater = matrix2 > 20
print(greater)

[[False False False]
 [False False False]
 [False False  True]
 [ True  True  True]]


In [ ]:
#vector operations (1D array)
vector = np.array([3,7,9])
#calculating magnitude of vector
magnitude = np.linalg.norm(vector)
print(magnitude)

11.789826122551595


In [ ]:
#dot product or matrix multiplication
matrix1 = np.arange(1,13).reshape(4,3)
matrix2 = np.arange(13,25).reshape(3,4)
result  = np.dot(matrix1,matrix2)
print(result)

[[110 116 122 128]
 [263 278 293 308]
 [416 440 464 488]
 [569 602 635 668]]



## Array Functions
* max/min/sum/prod
* mean/median/std/var
* trigonometric functions
* dot product
* log & exponents
* round/floor/ceil

In [ ]:
matrix1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
#max: returns the maximum value of the array elements.
print(np.max(matrix1))
print(np.max(matrix1,axis=1)) #axix=1, return max of rows

12
[ 3  6  9 12]


In [ ]:
#min: returns the minimum value of the array elements.
print(np.min(matrix1))
print(np.min(matrix1,axis=0)) #axis=0, return min of columns

1
[1 2 3]


In [ ]:
#sum: computes the sum of all elements in the array

In [ ]:
np.sum(matrix1)

78

In [ ]:
#prod: computes the product of all elements in the array.
np.prod(matrix1)

479001600

In [ ]:
#mean/median/standard deviation/variance
print(np.mean(matrix1))
print(np.median(matrix1))
print(np.std(matrix1))
print(np.var(matrix1))

6.5
6.5
3.452052529534663
11.916666666666666


In [ ]:
#trigonometric functions
np.cos(matrix1)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026],
       [-0.83907153,  0.0044257 ,  0.84385396]])

In [ ]:
#log & exponents

In [ ]:
print(matrix1)
np.log(matrix1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458],
       [2.30258509, 2.39789527, 2.48490665]])

In [ ]:
#Calculates the exponential of all elements in the array.
#The base is e (Euler's number, approximately 2.718).
np.exp(matrix1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

In [ ]:
#exp2: Calculates 2^x for all elements in the array.
np.exp2(matrix1)


array([[2.000e+00, 4.000e+00, 8.000e+00],
       [1.600e+01, 3.200e+01, 6.400e+01],
       [1.280e+02, 2.560e+02, 5.120e+02],
       [1.024e+03, 2.048e+03, 4.096e+03]])

In [ ]:
#round/floor/ceil
a1 = np.random.random((3,4))
print(a1)
print(np.ceil(a1))

[[0.31188557 0.53155197 0.23708502 0.69965605]
 [0.03820944 0.38295116 0.52155893 0.80781428]
 [0.05362785 0.60570286 0.00914111 0.83502264]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
print(np.floor(a1))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
print(np.round(a1))

[[0. 1. 0. 1.]
 [0. 0. 1. 1.]
 [0. 1. 0. 1.]]


## Indexing & Slicing

In [ ]:
m1 = np.arange(10)
m2 = np.arange(12).reshape(3,4)
m3 = np.arange(8).reshape(2,2,2)
print(m1)
print(m2)
print(m3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
#Extracting elements from arrays.
m1[2] #index2

2

In [ ]:
m2[1,2] #6

6

In [ ]:
m2[2,0]

8

In [ ]:
print(m3)
m3[0,0,1]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


1

In [ ]:
m1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
m1[1:7:3]

array([1, 4])

In [ ]:
m2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
m2[0:2,0::2]

array([[0, 2],
       [4, 6]])

## Iterating

In [ ]:
for i in matrix2:
  print(i)

[13 14 15 16]
[17 18 19 20]
[21 22 23 24]


In [ ]:
#nditer
for i in np.nditer(matrix2):
  print(i)

13
14
15
16
17
18
19
20
21
22
23
24


## Reshaping

In [ ]:
matrix2

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [ ]:
#transpose
np.transpose(matrix2)

array([[13, 17, 21],
       [14, 18, 22],
       [15, 19, 23],
       [16, 20, 24]])

In [ ]:
#ravel: The np.ravel function is used to flatten a
#multi-dimensional array into a contiguous 1D array.
np.ravel(matrix2)

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

## Stacking

In [ ]:
#Stacking refers to combining multiple arrays along a new axis.
#Vertical Stacking
a1 = [1,2,3]
a2 = [4,5,6]
np.vstack((a1,a2))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#Horizontal Stacking
np.hstack((a1,a2))

array([1, 2, 3, 4, 5, 6])

## Splitting

In [ ]:
matrix1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
#vertical
np.vsplit(matrix1,2)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]